### express的错误处理

- 可以将需要执行错误的执行next让一个统一执行报错信息

- ```
  app.post("/login", (req, res, next) => {
    const isLogin = false;
    if (isLogin) {
      res.json("user login");
    } else {
      next(new Error(USERNAME_DOES_NOT_EXISTS));
    }
  });
  
  ```

  

- 统一执行报错

```
app.use((err, req, res, next) => {
  let status = 400;
  let message = "";

  switch (err.message) {
    case USERNAME_ALREADY_EXISTS:
      message = "username does not exists";
      break;
    case USERNAME_ALREADY_EXISTS:
      message = "username already exist";
      break;
    default:
      message = "NOT FOUND~";
  }
  res.status(status);
  res.json({
    errCode: status,
    errMessage: message,
  });
});
```





